### ISSUE TITLE
recommended DuplicateNumberLiteral.ignoreNumbers config invalid

### ISSUE THREAD

**Issue by lienharc** [nvuillam/npm-groovy-lint#442]
The setting for ignoreNumbers in the recommended config (https://github.com/nvuillam/npm-groovy-lint/blob/main/lib/.groovylintrc-recommended.json) seems to be invalid for me.

Switching from a (json) list to a string with commas-separated values fixes the issue for me.
```yaml
extends: "recommended"
rules:
  dry.DuplicateNumberLiteral:
    ignoreNumbers: '0,1,2,3,-1'
```

### System Info

```
GroovyLint: Successfully processed CodeNarc: 
CodeNarc version 3.5.0
npm-groovy-lint version 15.0.2

Embeds:
CodeNarc version 3.5.0
- Groovy version 3.0.9 (superlite)
```
